import type { Language, Route, UiCopy } from "./types";

export const ROUTES: Route[] = ["landing", "overview", "workspace", "usage", "benchmarks"];
export const SERIES_COLORS = ["#47b4ff", "#ff982b", "#f2c14f", "#ff5d7b", "#7f7cff", "#9ba6b2"];
export const TOPIC_COLORS = ["#ff982b", "#47b4ff", "#ff5d7b", "#f2c14f", "#7f7cff", "#9ba6b2"];
export const THEME_KEY = "caos-lda-hsi-theme";

export const FALLBACK_PTM_SUPERVISION_PRINCIPLE =
  "Topics are treated as latent regime layers. Flat theta-feature models are control baselines only; routed, soft-expert, or hierarchical variants are the canonical supervised PTM targets when available.";

export const FALLBACK_CLASSIFICATION_MODEL_ROLES: Record<string, string> = {
  raw_logistic_regression: "raw-spectral-baseline",
  pca_logistic_regression: "reduced-feature-baseline",
  topic_logistic_regression: "flat-topic-control-baseline",
  cube_topic_logistic_regression: "aggregated-topic-control-baseline",
  region_topic_logistic_regression: "regional-topic-control-baseline"
};

export const FALLBACK_REGRESSION_MODEL_ROLES: Record<string, string> = {
  raw_ridge_regression: "raw-spectral-baseline",
  pls_regression: "latent-linear-baseline",
  topic_mixture_linear_regression: "flat-topic-control-baseline",
  cube_topic_mixture_linear_regression: "aggregated-topic-control-baseline",
  region_topic_mixture_linear_regression: "regional-topic-control-baseline",
  topic_routed_linear_regression: "topic-routed-primary-ptm-model"
};

export const UI: Record<Language, UiCopy> = {
  es: {
    allDatasets: "Datasets catalogados",
    benchmarksTitle: "Benchmarks locales y contrato de validacion",
    codeOffline: "Codigo y flujo offline",
    datasetSearch: "Buscar dataset, dominio, modalidad o fuente",
    datasetView: "Vista de dataset",
    empty: "Sin datos disponibles",
    emptyWorkspace: "Selecciona una familia y un subconjunto para abrir el workspace.",
    evidenceContract: "Contrato de evidencia",
    evidenceView: "Evidencia",
    flowTitle: "Flujo de trabajo local",
    inferenceView: "Inferencia",
    landingIntro: "Un workspace local-first para probar si poblaciones espectrales pueden reorganizarse como corpus, topicos y rutas de inferencia.",
    loading: "Cargando workspace",
    loadingHint: "La app consume artefactos locales versionados generados por el pipeline offline.",
    measuredFamily: "Familia D: regiones con mediciones",
    methodsTitle: "Representaciones, corpus y teoria operativa",
    methodView: "Metodo",
    noInference: "Este subconjunto todavia no publica una tarjeta de inferencia.",
    openOverview: "Abrir overview",
    openRepo: "Abrir repo",
    overviewIntro: "El objetivo aqui no es mostrar una web decorativa. El objetivo es hacer visible la estructura cientifica: familias de datos, definiciones de documento, corpus, topicos y limites de validacion.",
    paperLinks: "Papers, dataset hubs y enlaces de contexto",
    routeBenchmarks: "Benchmarks",
    routeLanding: "Landing",
    routeOverview: "Overview",
    routeUsage: "Uso",
    routeWorkspace: "Workspace",
    setupCommands: "Comandos locales",
    subsetRegistry: "Subconjuntos interactivos",
    summary: "Resumen",
    topicsTitle: "Topicos, mezclas y tokens",
    topicsView: "Topicos",
    usageIntro: "El repo debe explicar como reproducir el pipeline, no solo como abrir la app. Esta pagina deja claro que scripts, carpetas y salidas sostienen la interfaz.",
    validationTitle: "Reglas de validacion",
    workspaceIntro: "El flujo parte por familia y subset. La UI no amontona todo; deja entrar a evidencia, metodo, topicos e inferencia como superficies separadas."
  },
  en: {
    allDatasets: "Cataloged datasets",
    benchmarksTitle: "Local benchmarks and validation contract",
    codeOffline: "Offline code and flow",
    datasetSearch: "Search dataset, domain, modality, or source",
    datasetView: "Dataset view",
    empty: "No data available",
    emptyWorkspace: "Choose a family and subset to open the workspace.",
    evidenceContract: "Evidence contract",
    evidenceView: "Evidence",
    flowTitle: "Local workflow",
    inferenceView: "Inference",
    landingIntro: "A local-first workspace for testing whether spectral populations can be reorganized as corpora, topics, and inference routes.",
    loading: "Loading workspace",
    loadingHint: "The app projects versioned local artifacts generated by the offline pipeline.",
    measuredFamily: "Family D: regions with measurements",
    methodsTitle: "Representations, corpora, and operational theory",
    methodView: "Method",
    noInference: "This subset does not publish an inference card yet.",
    openOverview: "Open overview",
    openRepo: "Open repo",
    overviewIntro: "The goal here is not a decorative website. The goal is to expose the scientific structure: data families, document definitions, corpora, topics, and validation limits.",
    paperLinks: "Papers, dataset hubs, and context links",
    routeBenchmarks: "Benchmarks",
    routeLanding: "Landing",
    routeOverview: "Overview",
    routeUsage: "Usage",
    routeWorkspace: "Workspace",
    setupCommands: "Local commands",
    subsetRegistry: "Interactive subsets",
    summary: "Summary",
    topicsTitle: "Topics, mixtures, and tokens",
    topicsView: "Topics",
    usageIntro: "The repo must explain how to reproduce the pipeline, not only how to open the app. This page makes explicit which scripts, folders, and outputs sustain the interface.",
    validationTitle: "Validation rules",
    workspaceIntro: "The flow begins with family and subset. The UI does not dump everything at once; it exposes evidence, method, topics, and inference as separate surfaces."
  }
};
